In [167]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import plotly.express as px
import statistics as stats
from scipy import stats as st
import geopandas as gpd

DATA LOADING

In [168]:
Country = pd.read_csv('country_latest.csv')
Health_indicators = pd.read_csv('health_indicators.csv')
indicator_data = pd.read_csv('indicator_metadata.csv')

In [169]:
Country.head()

,country_code,country_name,region,income_level,indicator_code,indicator_name,value,year
0,AFG,Afghanistan,"Middle East, North Africa, Afghanistan & Pakistan",Low income,SP.POP.TOTL,"Population, total",42647492.0,2024
1,ALB,Albania,Europe & Central Asia,Upper middle income,SP.POP.TOTL,"Population, total",2377128.0,2024
2,DZA,Algeria,"Middle East, North Africa, Afghanistan & Pakistan",Upper middle income,SP.POP.TOTL,"Population, total",46814308.0,2024
3,ASM,American Samoa,East Asia & Pacific,High income,SP.POP.TOTL,"Population, total",46765.0,2024
4,AND,Andorra,Europe & Central Asia,High income,SP.POP.TOTL,"Population, total",81938.0,2024

In [170]:
Health_indicators.head()

,country_code,country_name,region,income_level,year,population,population_growth,urban_pct,life_expectancy,life_expectancy_male,...,stunting_pct,wasting_pct,overweight_children_pct,undernourishment_pct,fertility_rate,adolescent_fertility,prenatal_care_pct,gdp_per_capita,gdp_per_capita_ppp,poverty_rate
0,ABW,Aruba,Latin America & Caribbean,High income,2000,90588.0,1.030817,65.354550,72.939,70.149,...,NaN,NaN,NaN,NaN,1.845,43.729,NaN,20681.023027,30245.706974,NaN
1,ABW,Aruba,Latin America & Caribbean,High income,2001,91439.0,0.935033,65.335114,73.044,70.251,...,NaN,NaN,NaN,NaN,1.813,40.463,NaN,20740.132583,31920.239073,NaN
2,ABW,Aruba,Latin America & Caribbean,High income,2002,92074.0,0.692052,65.282069,73.135,70.364,...,NaN,NaN,NaN,NaN,1.800,38.185,NaN,21307.248251,31888.508737,NaN
3,ABW,Aruba,Latin America & Caribbean,High income,2003,93128.0,1.138229,65.198292,73.236,70.488,...,NaN,NaN,NaN,NaN,1.808,37.807,NaN,21949.485996,32507.084315,NaN
4,ABW,Aruba,Latin America & Caribbean,High income,2004,95138.0,2.135358,65.088653,73.223,70.487,...,NaN,NaN,NaN,NaN,1.819,38.761,NaN,23700.631990,35059.273098,NaN

In [171]:
indicator_data.head()

,indicator_code,indicator_name,category,unit,description
0,SP.POP.TOTL,"Population, total",Demographics,count,"Population, total (Demographics)"
1,SP.POP.GROW,Population growth (annual %),Demographics,%,Population growth (annual %) (Demographics)
2,SP.URB.TOTL.IN.ZS,Urban population (% of total),Demographics,%,Urban population (% of total) (Demographics)
3,SP.DYN.LE00.IN,"Life expectancy at birth, total",Demographics,years,"Life expectancy at birth, total (Demographics)"
4,SP.DYN.LE00.MA.IN,"Life expectancy, male",Demographics,years,"Life expectancy, male (Demographics)"

In [172]:
Country.info()

<class 'pandas.DataFrame'>
RangeIndex: 7802 entries, 0 to 7801
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   country_code    7802 non-null   str
 1   country_name    7802 non-null   str
 2   region          7802 non-null   str
 3   income_level    7802 non-null   str
 4   indicator_code  7802 non-null   str
 5   indicator_name  7802 non-null   str
 6   value           7802 non-null   float64
 7   year            7802 non-null   int64
dtypes: float64(1), int64(1), str(6)
memory usage: 1.2 MB

In [173]:
Health_indicators.info()

<class 'pandas.DataFrame'>
RangeIndex: 5275 entries, 0 to 5274
Data columns (total 48 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   country_code                   5275 non-null   str
 1   country_name                   5275 non-null   str
 2   region                         5275 non-null   str
 3   income_level                   5275 non-null   str
 4   year                           5275 non-null   int64
 5   population                     5275 non-null   float64
 6   population_growth              5274 non-null   float64
 7   urban_pct                      5275 non-null   float64
 8   life_expectancy                5275 non-null   float64
 9   life_expectancy_male           5275 non-null   float64
 10  life_expectancy_female         5275 non-null   float64
 11  death_rate                     5275 non-null   float64
 12  birth_rate                     5275 non-null   float64
 13  health_expenditure_pct_gdp     4514 non-null   float64
 14  health_expenditure_per_capita  4511 non-null   float64
 15  physicians_per_1000            2831 non-null   float64
 16  hospital_beds_per_1000         2898 non-null   float64
 17  nurses_per_1000                2832 non-null   float64
 18  under5_mortality               4850 non-null   float64
 19  neonatal_mortality             4850 non-null   float64
 20  maternal_mortality             4608 non-null   float64
 21  tb_incidence                   5057 non-null   float64
 22  hiv_incidence                  3614 non-null   float64
 23  communicable_death_pct         1098 non-null   float64
 24  noncommunicable_death_pct      1098 non-null   float64
 25  smoking_male                   1304 non-null   float64
 26  smoking_female                 1304 non-null   float64
 27  obesity_pct                    0 non-null      float64
 28  alcohol_per_capita             3870 non-null   float64
 29  diabetes_pct                   420 non-null    float64
 30  safe_water_pct                 3591 non-null   float64
 31  sanitation_pct                 3469 non-null   float64
 32  handwashing_pct                1781 non-null   float64
 33  immunization_measles           4755 non-null   float64
 34  immunization_dpt               4755 non-null   float64
 35  immunization_bcg               3882 non-null   float64
 36  immunization_pol3              4755 non-null   float64
 37  immunization_hib3              3733 non-null   float64
 38  stunting_pct                   844 non-null    float64
 39  wasting_pct                    843 non-null    float64
 40  overweight_children_pct        806 non-null    float64
 41  undernourishment_pct           3762 non-null   float64
 42  fertility_rate                 5275 non-null   float64
 43  adolescent_fertility           5275 non-null   float64
 44  prenatal_care_pct              741 non-null    float64
 45  gdp_per_capita                 5110 non-null   float64
 46  gdp_per_capita_ppp             4838 non-null   float64
 47  poverty_rate                   1827 non-null   float64
dtypes: float64(43), int64(1), str(4)
memory usage: 2.2 MB

In [174]:
Health_indicators.describe()

,year,population,population_growth,urban_pct,life_expectancy,life_expectancy_male,life_expectancy_female,death_rate,birth_rate,health_expenditure_pct_gdp,...,stunting_pct,wasting_pct,overweight_children_pct,undernourishment_pct,fertility_rate,adolescent_fertility,prenatal_care_pct,gdp_per_capita,gdp_per_capita_ppp,poverty_rate
count,5275.000000,5.275000e+03,5274.000000,5275.000000,5275.000000,5275.000000,5275.000000,5275.000000,5275.000000,4514.000000,...,844.000000,843.000000,806.000000,3762.000000,5275.000000,5275.000000,741.000000,5110.000000,4838.000000,1827.000000
mean,2012.000000,3.378305e+07,1.280475,58.716732,70.748244,68.215760,73.394403,8.192702,21.095707,6.222646,...,24.009360,5.896679,6.198015,10.937400,2.797145,51.097317,86.791826,15749.091058,19781.847712,9.492118
std,7.211786,1.323408e+08,1.618914,23.674753,8.701547,8.471691,9.066795,3.412191,10.888048,2.867900,...,15.043393,4.401812,4.499476,11.043652,1.468998,42.893201,16.137098,25074.200336,22391.204701,17.142033
min,2000.000000,9.544000e+03,-11.356645,8.043814,14.665000,12.383000,20.006000,0.841000,4.200000,1.222602,...,0.500000,0.100000,0.000000,2.500000,0.721000,0.505000,16.100000,109.593814,403.983197,0.000000
25%,2006.000000,7.743870e+05,0.297465,39.060949,65.356000,62.722000,67.976000,6.033500,11.746000,4.126287,...,10.800000,2.400000,2.725000,2.500000,1.670000,15.427500,82.500000,1544.567936,3899.860735,0.300000
50%,2012.000000,5.943366e+06,1.175030,60.031069,72.442000,69.217000,75.689000,7.607000,18.172000,5.640688,...,23.800000,4.900000,5.300000,6.300000,2.274000,39.131000,92.800000,5356.365656,11309.514697,1.500000
75%,2018.000000,2.201484e+07,2.210221,77.627285,77.197000,74.500000,80.115000,9.780500,28.806500,7.966407,...,35.325000,8.700000,8.700000,15.600000,3.638500,75.234000,97.600000,20032.321089,28679.803239,9.800000
max,2024.000000,1.450936e+09,21.700343,100.000000,86.497000,84.560000,88.626000,72.483000,53.390000,27.089685,...,64.000000,24.600000,29.600000,72.500000,7.829000,206.357000,100.000000,288001.433369,180939.439450,94.900000

DATA CLEANING

In [175]:
print(Health_indicators.columns.tolist())

['country_code', 'country_name', 'region', 'income_level', 'year', 'population', 'population_growth', 'urban_pct', 'life_expectancy', 'life_expectancy_male', 'life_expectancy_female', 'death_rate', 'birth_rate', 'health_expenditure_pct_gdp', 'health_expenditure_per_capita', 'physicians_per_1000', 'hospital_beds_per_1000', 'nurses_per_1000', 'under5_mortality', 'neonatal_mortality', 'maternal_mortality', 'tb_incidence', 'hiv_incidence', 'communicable_death_pct', 'noncommunicable_death_pct', 'smoking_male', 'smoking_female', 'obesity_pct', 'alcohol_per_capita', 'diabetes_pct', 'safe_water_pct', 'sanitation_pct', 'handwashing_pct', 'immunization_measles', 'immunization_dpt', 'immunization_bcg', 'immunization_pol3', 'immunization_hib3', 'stunting_pct', 'wasting_pct', 'overweight_children_pct', 'undernourishment_pct', 'fertility_rate', 'adolescent_fertility', 'prenatal_care_pct', 'gdp_per_capita', 'gdp_per_capita_ppp', 'poverty_rate']

In [176]:
# Capitalising the column names 

Health_indicators.columns = Health_indicators.columns.str.title()
Country.columns = Country.columns.str.title()
indicator_data.columns = indicator_data.columns.str.title()

In [177]:
Country.head()

,Country_Code,Country_Name,Region,Income_Level,Indicator_Code,Indicator_Name,Value,Year
0,AFG,Afghanistan,"Middle East, North Africa, Afghanistan & Pakistan",Low income,SP.POP.TOTL,"Population, total",42647492.0,2024
1,ALB,Albania,Europe & Central Asia,Upper middle income,SP.POP.TOTL,"Population, total",2377128.0,2024
2,DZA,Algeria,"Middle East, North Africa, Afghanistan & Pakistan",Upper middle income,SP.POP.TOTL,"Population, total",46814308.0,2024
3,ASM,American Samoa,East Asia & Pacific,High income,SP.POP.TOTL,"Population, total",46765.0,2024
4,AND,Andorra,Europe & Central Asia,High income,SP.POP.TOTL,"Population, total",81938.0,2024

In [178]:
# Removing the _ sign from the column names

Health_indicators.columns = Health_indicators.columns.str.replace('_', ' ')
Country.columns = Country.columns.str.replace('_', ' ')
indicator_data.columns = indicator_data.columns.str.replace('_', ' ')

In [179]:
Health_indicators.head()

,Country Code,Country Name,Region,Income Level,Year,Population,Population Growth,Urban Pct,Life Expectancy,Life Expectancy Male,...,Stunting Pct,Wasting Pct,Overweight Children Pct,Undernourishment Pct,Fertility Rate,Adolescent Fertility,Prenatal Care Pct,Gdp Per Capita,Gdp Per Capita Ppp,Poverty Rate
0,ABW,Aruba,Latin America & Caribbean,High income,2000,90588.0,1.030817,65.354550,72.939,70.149,...,NaN,NaN,NaN,NaN,1.845,43.729,NaN,20681.023027,30245.706974,NaN
1,ABW,Aruba,Latin America & Caribbean,High income,2001,91439.0,0.935033,65.335114,73.044,70.251,...,NaN,NaN,NaN,NaN,1.813,40.463,NaN,20740.132583,31920.239073,NaN
2,ABW,Aruba,Latin America & Caribbean,High income,2002,92074.0,0.692052,65.282069,73.135,70.364,...,NaN,NaN,NaN,NaN,1.800,38.185,NaN,21307.248251,31888.508737,NaN
3,ABW,Aruba,Latin America & Caribbean,High income,2003,93128.0,1.138229,65.198292,73.236,70.488,...,NaN,NaN,NaN,NaN,1.808,37.807,NaN,21949.485996,32507.084315,NaN
4,ABW,Aruba,Latin America & Caribbean,High income,2004,95138.0,2.135358,65.088653,73.223,70.487,...,NaN,NaN,NaN,NaN,1.819,38.761,NaN,23700.631990,35059.273098,NaN

In [180]:
Country.head()

,Country Code,Country Name,Region,Income Level,Indicator Code,Indicator Name,Value,Year
0,AFG,Afghanistan,"Middle East, North Africa, Afghanistan & Pakistan",Low income,SP.POP.TOTL,"Population, total",42647492.0,2024
1,ALB,Albania,Europe & Central Asia,Upper middle income,SP.POP.TOTL,"Population, total",2377128.0,2024
2,DZA,Algeria,"Middle East, North Africa, Afghanistan & Pakistan",Upper middle income,SP.POP.TOTL,"Population, total",46814308.0,2024
3,ASM,American Samoa,East Asia & Pacific,High income,SP.POP.TOTL,"Population, total",46765.0,2024
4,AND,Andorra,Europe & Central Asia,High income,SP.POP.TOTL,"Population, total",81938.0,2024

In [181]:
indicator_data.head()

,Indicator Code,Indicator Name,Category,Unit,Description
0,SP.POP.TOTL,"Population, total",Demographics,count,"Population, total (Demographics)"
1,SP.POP.GROW,Population growth (annual %),Demographics,%,Population growth (annual %) (Demographics)
2,SP.URB.TOTL.IN.ZS,Urban population (% of total),Demographics,%,Urban population (% of total) (Demographics)
3,SP.DYN.LE00.IN,"Life expectancy at birth, total",Demographics,years,"Life expectancy at birth, total (Demographics)"
4,SP.DYN.LE00.MA.IN,"Life expectancy, male",Demographics,years,"Life expectancy, male (Demographics)"

In [182]:
Health_indicators.dtypes

Country Code                         str
Country Name                         str
Region                               str
Income Level                         str
Year                               int64
Population                       float64
Population Growth                float64
Urban Pct                        float64
Life Expectancy                  float64
Life Expectancy Male             float64
Life Expectancy Female           float64
Death Rate                       float64
Birth Rate                       float64
Health Expenditure Pct Gdp       float64
Health Expenditure Per Capita    float64
Physicians Per 1000              float64
Hospital Beds Per 1000           float64
Nurses Per 1000                  float64
Under5 Mortality                 float64
Neonatal Mortality               float64
Maternal Mortality               float64
Tb Incidence                     float64
Hiv Incidence                    float64
Communicable Death Pct           float64
Noncommunicable Death Pct        float64
Smoking Male                     float64
Smoking Female                   float64
Obesity Pct                      float64
Alcohol Per Capita               float64
Diabetes Pct                     float64
Safe Water Pct                   float64
Sanitation Pct                   float64
Handwashing Pct                  float64
Immunization Measles             float64
Immunization Dpt                 float64
Immunization Bcg                 float64
Immunization Pol3                float64
Immunization Hib3                float64
Stunting Pct                     float64
Wasting Pct                      float64
Overweight Children Pct          float64
Undernourishment Pct             float64
Fertility Rate                   float64
Adolescent Fertility             float64
Prenatal Care Pct                float64
Gdp Per Capita                   float64
Gdp Per Capita Ppp               float64
Poverty Rate                     float64
dtype: object

In [183]:
# Converting to the correct data types 

Health_indicators = Health_indicators.convert_dtypes()
Country = Country.convert_dtypes()
Indicator_data = indicator_data.convert_dtypes()

In [184]:
Health_indicators.info()

<class 'pandas.DataFrame'>
RangeIndex: 5275 entries, 0 to 5274
Data columns (total 48 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country Code                   5275 non-null   string
 1   Country Name                   5275 non-null   string
 2   Region                         5275 non-null   string
 3   Income Level                   5275 non-null   string
 4   Year                           5275 non-null   Int64
 5   Population                     5275 non-null   Int64
 6   Population Growth              5274 non-null   Float64
 7   Urban Pct                      5275 non-null   Float64
 8   Life Expectancy                5275 non-null   Float64
 9   Life Expectancy Male           5275 non-null   Float64
 10  Life Expectancy Female         5275 non-null   Float64
 11  Death Rate                     5275 non-null   Float64
 12  Birth Rate                     5275 non-null   Float64
 13  Health Expenditure Pct Gdp     4514 non-null   Float64
 14  Health Expenditure Per Capita  4511 non-null   Float64
 15  Physicians Per 1000            2831 non-null   Float64
 16  Hospital Beds Per 1000         2898 non-null   Float64
 17  Nurses Per 1000                2832 non-null   Float64
 18  Under5 Mortality               4850 non-null   Float64
 19  Neonatal Mortality             4850 non-null   Float64
 20  Maternal Mortality             4608 non-null   Int64
 21  Tb Incidence                   5057 non-null   Float64
 22  Hiv Incidence                  3614 non-null   Float64
 23  Communicable Death Pct         1098 non-null   Float64
 24  Noncommunicable Death Pct      1098 non-null   Float64
 25  Smoking Male                   1304 non-null   Float64
 26  Smoking Female                 1304 non-null   Float64
 27  Obesity Pct                    0 non-null      Int64
 28  Alcohol Per Capita             3870 non-null   Float64
 29  Diabetes Pct                   420 non-null    Float64
 30  Safe Water Pct                 3591 non-null   Float64
 31  Sanitation Pct                 3469 non-null   Float64
 32  Handwashing Pct                1781 non-null   Float64
 33  Immunization Measles           4755 non-null   Int64
 34  Immunization Dpt               4755 non-null   Int64
 35  Immunization Bcg               3882 non-null   Int64
 36  Immunization Pol3              4755 non-null   Int64
 37  Immunization Hib3              3733 non-null   Int64
 38  Stunting Pct                   844 non-null    Float64
 39  Wasting Pct                    843 non-null    Float64
 40  Overweight Children Pct        806 non-null    Float64
 41  Undernourishment Pct           3762 non-null   Float64
 42  Fertility Rate                 5275 non-null   Float64
 43  Adolescent Fertility           5275 non-null   Float64
 44  Prenatal Care Pct              741 non-null    Float64
 45  Gdp Per Capita                 5110 non-null   Float64
 46  Gdp Per Capita Ppp             4838 non-null   Float64
 47  Poverty Rate                   1827 non-null   Float64
dtypes: Float64(35), Int64(9), string(4)
memory usage: 2.4 MB

In [185]:

#Removing trailing and leading spaces from column 

Health_indicators.columns = Health_indicators.columns.str.strip()
Country.columns = Country.columns.str.strip()
indicator_data.columns = indicator_data.columns.str.strip()

In [186]:
Country.head()

,Country Code,Country Name,Region,Income Level,Indicator Code,Indicator Name,Value,Year
0,AFG,Afghanistan,"Middle East, North Africa, Afghanistan & Pakistan",Low income,SP.POP.TOTL,"Population, total",42647492.0,2024
1,ALB,Albania,Europe & Central Asia,Upper middle income,SP.POP.TOTL,"Population, total",2377128.0,2024
2,DZA,Algeria,"Middle East, North Africa, Afghanistan & Pakistan",Upper middle income,SP.POP.TOTL,"Population, total",46814308.0,2024
3,ASM,American Samoa,East Asia & Pacific,High income,SP.POP.TOTL,"Population, total",46765.0,2024
4,AND,Andorra,Europe & Central Asia,High income,SP.POP.TOTL,"Population, total",81938.0,2024

In [187]:
# Checking for missing values in the datasets

print(Health_indicators.isnull().sum())
print(Country.isnull().sum())
print(indicator_data.isnull().sum())

Country Code                        0
Country Name                        0
Region                              0
Income Level                        0
Year                                0
Population                          0
Population Growth                   1
Urban Pct                           0
Life Expectancy                     0
Life Expectancy Male                0
Life Expectancy Female              0
Death Rate                          0
Birth Rate                          0
Health Expenditure Pct Gdp        761
Health Expenditure Per Capita     764
Physicians Per 1000              2444
Hospital Beds Per 1000           2377
Nurses Per 1000                  2443
Under5 Mortality                  425
Neonatal Mortality                425
Maternal Mortality                667
Tb Incidence                      218
Hiv Incidence                    1661
Communicable Death Pct           4177
Noncommunicable Death Pct        4177
Smoking Male                     3971
Smoking Female                   3971
Obesity Pct                      5275
Alcohol Per Capita               1405
Diabetes Pct                     4855
Safe Water Pct                   1684
Sanitation Pct                   1806
Handwashing Pct                  3494
Immunization Measles              520
Immunization Dpt                  520
Immunization Bcg                 1393
Immunization Pol3                 520
Immunization Hib3                1542
Stunting Pct                     4431
Wasting Pct                      4432
Overweight Children Pct          4469
Undernourishment Pct             1513
Fertility Rate                      0
Adolescent Fertility                0
Prenatal Care Pct                4534
Gdp Per Capita                    165
Gdp Per Capita Ppp                437
Poverty Rate                     3448
dtype: int64
Country Code      0
Country Name      0
Region            0
Income Level      0
Indicator Code    0
Indicator Name    0
Value             0
Year              0
dtype: int64
Indicator Code    0
Indicator Name    0
Category          0
Unit              0
Description       0
dtype: int64

In [188]:
print(Country.isnull().sum())

Country Code      0
Country Name      0
Region            0
Income Level      0
Indicator Code    0
Indicator Name    0
Value             0
Year              0
dtype: int64

In [189]:
# sum of missing values in indicator_data

print(indicator_data.isnull().sum())

Indicator Code    0
Indicator Name    0
Category          0
Unit              0
Description       0
dtype: int64

In [190]:
# percentage of missing values in each column

missing_pct = (Health_indicators.isna().sum() / len(Health_indicators) * 100).sort_values(ascending=False)
print(missing_pct)

Obesity Pct                      100.000000
Diabetes Pct                      92.037915
Prenatal Care Pct                 85.952607
Overweight Children Pct           84.720379
Wasting Pct                       84.018957
Stunting Pct                      84.000000
Noncommunicable Death Pct         79.184834
Communicable Death Pct            79.184834
Smoking Female                    75.279621
Smoking Male                      75.279621
Handwashing Pct                   66.236967
Poverty Rate                      65.364929
Physicians Per 1000               46.331754
Nurses Per 1000                   46.312796
Hospital Beds Per 1000            45.061611
Sanitation Pct                    34.236967
Safe Water Pct                    31.924171
Hiv Incidence                     31.488152
Immunization Hib3                 29.232227
Undernourishment Pct              28.682464
Alcohol Per Capita                26.635071
Immunization Bcg                  26.407583
Health Expenditure Per Capita     14.483412
Health Expenditure Pct Gdp        14.426540
Maternal Mortality                12.644550
Immunization Dpt                   9.857820
Immunization Measles               9.857820
Immunization Pol3                  9.857820
Gdp Per Capita Ppp                 8.284360
Under5 Mortality                   8.056872
Neonatal Mortality                 8.056872
Tb Incidence                       4.132701
Gdp Per Capita                     3.127962
Population Growth                  0.018957
Life Expectancy Female             0.000000
Death Rate                         0.000000
Birth Rate                         0.000000
Life Expectancy Male               0.000000
Population                         0.000000
Urban Pct                          0.000000
Country Name                       0.000000
Region                             0.000000
Country Code                       0.000000
Income Level                       0.000000
Life Expectancy                    0.000000
Year                               0.000000
Adolescent Fertility               0.000000
Fertility Rate                     0.000000
dtype: float64

In [191]:
# Dropping column with more than 50 % missing values

threshold = 50
cols_to_drop = missing_pct[missing_pct > threshold].index
Health_indicators = Health_indicators.drop(columns=cols_to_drop)
print(f"Dropped {len(cols_to_drop)} columns")

Dropped 12 columns

In [192]:
# Filling the missing numeric values

num_cols = Health_indicators.select_dtypes(include='number').columns

for col in num_cols:
    Health_indicators[col] = Health_indicators[col].fillna(Health_indicators[col].median())

In [193]:
# filling categorical missing values with mode
cat_cols = Health_indicators.select_dtypes(include='object').columns

for col in cat_cols:
    Health_indicators[col] = Health_indicators[col].fillna(Health_indicators[col].mode()[0])

In [194]:
Health_indicators.isnull().sum()

Country Code                     0
Country Name                     0
Region                           0
Income Level                     0
Year                             0
Population                       0
Population Growth                0
Urban Pct                        0
Life Expectancy                  0
Life Expectancy Male             0
Life Expectancy Female           0
Death Rate                       0
Birth Rate                       0
Health Expenditure Pct Gdp       0
Health Expenditure Per Capita    0
Physicians Per 1000              0
Hospital Beds Per 1000           0
Nurses Per 1000                  0
Under5 Mortality                 0
Neonatal Mortality               0
Maternal Mortality               0
Tb Incidence                     0
Hiv Incidence                    0
Alcohol Per Capita               0
Safe Water Pct                   0
Sanitation Pct                   0
Immunization Measles             0
Immunization Dpt                 0
Immunization Bcg                 0
Immunization Pol3                0
Immunization Hib3                0
Undernourishment Pct             0
Fertility Rate                   0
Adolescent Fertility             0
Gdp Per Capita                   0
Gdp Per Capita Ppp               0
dtype: int64

In [195]:
# verifying the total number of missing values in the dataset after filling the missing values

Health_indicators.isna().sum().sort_values(ascending=False)

Country Code                     0
Country Name                     0
Region                           0
Income Level                     0
Year                             0
Population                       0
Population Growth                0
Urban Pct                        0
Life Expectancy                  0
Life Expectancy Male             0
Life Expectancy Female           0
Death Rate                       0
Birth Rate                       0
Health Expenditure Pct Gdp       0
Health Expenditure Per Capita    0
Physicians Per 1000              0
Hospital Beds Per 1000           0
Nurses Per 1000                  0
Under5 Mortality                 0
Neonatal Mortality               0
Maternal Mortality               0
Tb Incidence                     0
Hiv Incidence                    0
Alcohol Per Capita               0
Safe Water Pct                   0
Sanitation Pct                   0
Immunization Measles             0
Immunization Dpt                 0
Immunization Bcg                 0
Immunization Pol3                0
Immunization Hib3                0
Undernourishment Pct             0
Fertility Rate                   0
Adolescent Fertility             0
Gdp Per Capita                   0
Gdp Per Capita Ppp               0
dtype: int64

In [196]:
print(Health_indicators.shape)
print(Health_indicators.info())

(5275, 36)
<class 'pandas.DataFrame'>
RangeIndex: 5275 entries, 0 to 5274
Data columns (total 36 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country Code                   5275 non-null   string
 1   Country Name                   5275 non-null   string
 2   Region                         5275 non-null   string
 3   Income Level                   5275 non-null   string
 4   Year                           5275 non-null   Int64
 5   Population                     5275 non-null   Int64
 6   Population Growth              5275 non-null   Float64
 7   Urban Pct                      5275 non-null   Float64
 8   Life Expectancy                5275 non-null   Float64
 9   Life Expectancy Male           5275 non-null   Float64
 10  Life Expectancy Female         5275 non-null   Float64
 11  Death Rate                     5275 non-null   Float64
 12  Birth Rate                     5275 non-null   Float64
 13  Health Expenditure Pct Gdp     5275 non-null   Float64
 14  Health Expenditure Per Capita  5275 non-null   Float64
 15  Physicians Per 1000            5275 non-null   Float64
 16  Hospital Beds Per 1000         5275 non-null   Float64
 17  Nurses Per 1000                5275 non-null   Float64
 18  Under5 Mortality               5275 non-null   Float64
 19  Neonatal Mortality             5275 non-null   Float64
 20  Maternal Mortality             5275 non-null   Int64
 21  Tb Incidence                   5275 non-null   Float64
 22  Hiv Incidence                  5275 non-null   Float64
 23  Alcohol Per Capita             5275 non-null   Float64
 24  Safe Water Pct                 5275 non-null   Float64
 25  Sanitation Pct                 5275 non-null   Float64
 26  Immunization Measles           5275 non-null   Int64
 27  Immunization Dpt               5275 non-null   Int64
 28  Immunization Bcg               5275 non-null   Int64
 29  Immunization Pol3              5275 non-null   Int64
 30  Immunization Hib3              5275 non-null   Int64
 31  Undernourishment Pct           5275 non-null   Float64
 32  Fertility Rate                 5275 non-null   Float64
 33  Adolescent Fertility           5275 non-null   Float64
 34  Gdp Per Capita                 5275 non-null   Float64
 35  Gdp Per Capita Ppp             5275 non-null   Float64
dtypes: Float64(24), Int64(8), string(4)
memory usage: 1.9 MB
None

In [197]:
Country.head()

,Country Code,Country Name,Region,Income Level,Indicator Code,Indicator Name,Value,Year
0,AFG,Afghanistan,"Middle East, North Africa, Afghanistan & Pakistan",Low income,SP.POP.TOTL,"Population, total",42647492.0,2024
1,ALB,Albania,Europe & Central Asia,Upper middle income,SP.POP.TOTL,"Population, total",2377128.0,2024
2,DZA,Algeria,"Middle East, North Africa, Afghanistan & Pakistan",Upper middle income,SP.POP.TOTL,"Population, total",46814308.0,2024
3,ASM,American Samoa,East Asia & Pacific,High income,SP.POP.TOTL,"Population, total",46765.0,2024
4,AND,Andorra,Europe & Central Asia,High income,SP.POP.TOTL,"Population, total",81938.0,2024

In [198]:
 # Saving the cleaned data to a new CSV file
Health_indicators.to_csv('cleaned_Health_indicators_data.csv', index=False)

In [199]:
Country.to_csv('cleaned_country_data.csv', index=False)

In [211]:
indicator_data.to_csv('cleaned_indicator_data.csv', index=False)

DATA MERGING

In [214]:
health = pd.read_csv("cleaned_health_indicators_data.csv")
country = pd.read_csv("cleaned_country_data.csv")
indicator = pd.read_csv("cleaned_indicator_data.csv")

In [215]:
country = country.rename(columns={"Value": "Population_2024"})

In [216]:
merged = health.merge(
country[["Country Code", "Population_2024"]],
on="Country Code",
how="left"
)

In [227]:
# Use the metadata frame that has the indicator key + category columns
meta = cleaned_indicator_data if "cleaned_indicator_data" in globals() else indicator
meta = meta.copy()

# Normalize column names to the ones used in the merge
rename_map = {}
for old, new in [("Indicator Code", "indicator_code"), ("Category", "category")]:
    if old in meta.columns and new not in meta.columns:
        rename_map[old] = new

meta = meta.rename(columns=rename_map)

# Keep only the columns needed for the merge
merge_cols = [c for c in ["indicator_code", "category"] if c in meta.columns]

if len(merge_cols) != 2:
    raise KeyError("Metadata dataframe does not contain both 'indicator_code' and 'category'")

merged = merged.merge(
    meta[merge_cols],
    on="indicator_code",
    how="left"
)
if "indicator_code" in merged.columns:
            pass
elif "Indicator Code" in merged.columns:
            merged = merged.rename(columns={"Indicator Code": "indicator_code"})
elif "Indicator Code" inhealth_df.columns:
            merged = merged.rename(columns={"Indicator Code": "indicator_code"})
else:
            raise KeyError("merged does not contain an indicator key column")

SyntaxError: invalid syntax (4248701488.py, line 28)